[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
'@chainlink/contracts/=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/v0.8/'
]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
